# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-24 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
