# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-24 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0002_auto_20170724_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='age',
            field=models.IntegerField(),
        ),
    ]
