# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-24 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.CharField(max_length=150)),
                ('institution', models.CharField(max_length=150)),
                ('program', models.CharField(max_length=150)),
                ('bio', models.TextField()),
            ],
        ),
    ]
