# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-27 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
    ]
